/**
 * BookStore APIs
 * BookStore APIs exposed from a Java EE back-end to an Angular front-end
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Book resource representation
 */
export class Book {
    /**
     * Identifier
     */
    id?: number;
    /**
     * Title of the book
     */
    title: string;
    /**
     * Description of the book
     */
    description?: string;
    /**
     * Unit Cost of the book
     */
    unitCost?: number;
    /**
     * ISBN of the book
     */
    isbn: string;
    /**
     * Publication Date of the book
     */
    publicationDate?: Date;
    /**
     * Number of pages of the book
     */
    nbOfPages?: number;
    /**
     * Image URL of the book
     */
    imageURL?: string;
    /**
     * Language book is written in
     */
    language?: Book.LanguageEnum;
}
export namespace Book {
    export type LanguageEnum = 'ENGLISH' | 'FRENCH' | 'SPANISH' | 'PORTUGUESE' | 'ITALIAN' | 'FINISH' | 'GERMAN' | 'DEUTSCH' | 'RUSSIAN';
    export const LanguageEnum = {
        ENGLISH: 'ENGLISH' as LanguageEnum,
        FRENCH: 'FRENCH' as LanguageEnum,
        SPANISH: 'SPANISH' as LanguageEnum,
        PORTUGUESE: 'PORTUGUESE' as LanguageEnum,
        ITALIAN: 'ITALIAN' as LanguageEnum,
        FINISH: 'FINISH' as LanguageEnum,
        GERMAN: 'GERMAN' as LanguageEnum,
        DEUTSCH: 'DEUTSCH' as LanguageEnum,
        RUSSIAN: 'RUSSIAN' as LanguageEnum
    }
}
// export namespace Book {
//     export enum LanguageEnum {
//         ENGLISH = <any> 'ENGLISH',
//         FRENCH = <any> 'FRENCH',
//         SPANISH = <any> 'SPANISH',
//         PORTUGUESE = <any> 'PORTUGUESE',
//         ITALIAN = <any> 'ITALIAN',
//         FINISH = <any> 'FINISH',
//         GERMAN = <any> 'GERMAN',
//         DUTCH = <any> 'DUTCH',
//         RUSSIAN = <any> 'RUSSIAN'
//     }
// }